'use client';

import React, { useState } from 'react';
import {
  Gavel, Copy, ExternalLink, CheckCircle2, ChevronRight,
  FileText, Shield, AlertTriangle, ArrowLeft,
} from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';
import type { AnalysisResponse } from '@/lib/api';

const PLATFORMS = [
  { id: 'x', name: 'X (Twitter)', icon: '𝕏', color: 'bg-neutral-800 dark:bg-neutral-200 dark:text-neutral-800', reportUrl: 'https://help.twitter.com/en/forms/safety-and-sensitive-content/deceptive-media' },
  { id: 'meta', name: 'Meta (Facebook/Instagram)', icon: 'Ⅎ', color: 'bg-blue-600', reportUrl: 'https://www.facebook.com/help/contact/567360926613498' },
  { id: 'tiktok', name: 'TikTok', icon: '♪', color: 'bg-pink-600', reportUrl: 'https://www.tiktok.com/legal/report/Copyright' },
  { id: 'youtube', name: 'YouTube', icon: '▶', color: 'bg-red-600', reportUrl: 'https://www.youtube.com/copyright_complaint_form' },
  { id: 'reddit', name: 'Reddit', icon: '◎', color: 'bg-orange-600', reportUrl: 'https://www.reddit.com/report' },
];

function generateDMCA(result: AnalysisResponse, platforms: string[]) {
  const date = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
  return `DMCA TAKEDOWN NOTICE
Under the Digital Millennium Copyright Act (17 U.S.C. § 512)

Date: ${date}

To Whom It May Concern,

I am writing to notify you of a deepfake — an AI-generated manipulated media — that infringes upon my rights and is currently hosted on your platform.

IDENTIFICATION OF INFRINGING MATERIAL:
The content in question is a digitally manipulated video/image that falsely depicts my likeness. This content was analyzed by the Trinetra Deepfake Detection Platform and confirmed as MANIPULATED with ${result.confidence_score.toFixed(1)}% confidence.

AI Analysis Details:
- Detection Verdict: ${result.primary_verdict}
- Confidence Score: ${result.confidence_score.toFixed(1)}%
- Local AI Model: ${result.local_label} (${result.local_confidence.toFixed(1)}%)
- Cloud Verification: ${result.rd_status || 'N/A'}
- Analysis Timestamp: ${new Date().toISOString()}

TARGET PLATFORMS: ${platforms.join(', ')}

STATEMENT OF GOOD FAITH:
I have a good faith belief that the use of this material is not authorized and constitutes an infringement of my rights, including my right to privacy, right of publicity, and protection from defamatory deepfake content.

STATEMENT OF ACCURACY:
The information in this notification is accurate, and under penalty of perjury, I am the person whose likeness has been misappropriated, or I am authorized to act on behalf of such person.

I request that you expeditiously remove or disable access to the infringing material.

Sincerely,
[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

---
This notice was generated by Trinetra Deepfake Detection Platform.
Forensic analysis ID: TRI-${Date.now().toString(36).toUpperCase()}`;
}

function generateCeaseDesist(result: AnalysisResponse) {
  const date = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
  return `CEASE AND DESIST LETTER

Date: ${date}

Dear [RECIPIENT NAME / UNKNOWN PARTY],

RE: DEMAND TO CEASE AND DESIST DISTRIBUTION OF DEEPFAKE CONTENT

I am writing to demand that you immediately cease and desist all distribution, sharing, and publication of AI-generated deepfake content that falsely depicts my likeness.

This content has been confirmed as digitally manipulated by the Trinetra Deepfake Detection Platform with a confidence score of ${result.confidence_score.toFixed(1)}%. The creation and distribution of non-consensual deepfake content violates multiple laws, including:

1. The IT Act, 2000 (India) — Sections 66E and 67
2. The Digital Personal Data Protection Act, 2023
3. Various state and federal laws regarding defamation, harassment, and invasion of privacy

DEMANDS:
1. Immediately remove ALL copies of the deepfake content from every platform
2. Destroy all copies of the deepfake content in your possession
3. Cease and desist from creating or distributing any further deepfake content depicting my likeness
4. Provide a written confirmation of compliance within 48 hours

CONSEQUENCES OF NON-COMPLIANCE:
Failure to comply with this demand will result in legal action, including but not limited to civil lawsuits for damages, injunctive relief, and reporting to law enforcement authorities.

This letter serves as formal notice. All rights are reserved.

Sincerely,
[YOUR NAME]
[YOUR ADDRESS]

---
Trinetra Forensic Report Reference: TRI-${Date.now().toString(36).toUpperCase()}`;
}

export const TakedownTab = ({ result }: { result: AnalysisResponse }) => {
  const [step, setStep] = useState(0);
  const [selected, setSelected] = useState<string[]>([]);
  const [copied, setCopied] = useState<string | null>(null);

  const togglePlatform = (id: string) => {
    setSelected(prev => prev.includes(id) ? prev.filter(p => p !== id) : [...prev, id]);
  };

  const copyText = (text: string, label: string) => {
    navigator.clipboard.writeText(text);
    setCopied(label);
    setTimeout(() => setCopied(null), 2000);
  };

  const selectedNames = PLATFORMS.filter(p => selected.includes(p.id)).map(p => p.name);
  const dmca = generateDMCA(result, selectedNames);
  const cd = generateCeaseDesist(result);

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="rounded-3xl border border-border bg-card p-8 shadow-soft">
        <div className="flex items-center gap-3 mb-4">
          <div className="h-11 w-11 rounded-2xl bg-gradient-to-br from-red-500 to-rose-600 flex items-center justify-center shadow-lg">
            <Gavel className="h-5 w-5 text-white" />
          </div>
          <div>
            <h2 className="font-display text-lg font-semibold">One-Click Takedown Wizard</h2>
            <p className="text-xs text-muted-foreground">Generate legal documents & report to platforms instantly</p>
          </div>
        </div>
        {/* Progress */}
        <div className="flex items-center gap-2 mt-6">
          {['Select Platforms', 'Review Documents', 'Submit Reports'].map((label, i) => (
            <React.Fragment key={label}>
              <div className={`flex items-center gap-2 px-3 py-1.5 rounded-full text-xs font-medium transition-colors ${
                i === step ? 'bg-foreground text-background' : i < step ? 'bg-emerald-500/10 text-emerald-600 dark:text-emerald-400' : 'bg-muted/60 text-muted-foreground'}`}>
                {i < step ? <CheckCircle2 className="h-3.5 w-3.5" /> : <span className="h-4 w-4 rounded-full border border-current flex items-center justify-center text-[10px]">{i + 1}</span>}
                <span className="hidden sm:inline">{label}</span>
              </div>
              {i < 2 && <ChevronRight className="h-3 w-3 text-muted-foreground" />}
            </React.Fragment>
          ))}
        </div>
      </div>

      <AnimatePresence mode="wait">
        {/* Step 1: Select Platforms */}
        {step === 0 && (
          <motion.div key="step0" initial={{ opacity: 0, x: 20 }} animate={{ opacity: 1, x: 0 }} exit={{ opacity: 0, x: -20 }}>
            <div className="rounded-3xl border border-border bg-card p-8 shadow-soft">
              <h3 className="font-display text-lg font-semibold mb-1">Where was the deepfake posted?</h3>
              <p className="text-xs text-muted-foreground mb-6">Select all platforms where the content has been shared</p>
              <div className="space-y-3">
                {PLATFORMS.map(p => (
                  <button key={p.id} onClick={() => togglePlatform(p.id)}
                    className={`w-full flex items-center gap-4 rounded-2xl border p-4 text-left transition-all ${
                      selected.includes(p.id) ? 'border-brand-orange/40 bg-brand-orange/5' : 'border-border hover:border-brand-orange/30 hover:bg-muted/30'}`}>
                    <div className={`h-10 w-10 rounded-xl ${p.color} flex items-center justify-center text-white text-lg font-bold shrink-0`}>{p.icon}</div>
                    <span className="text-sm font-medium flex-1">{p.name}</span>
                    {selected.includes(p.id) ? <CheckCircle2 className="h-5 w-5 text-brand-orange shrink-0" /> : <div className="h-5 w-5 rounded-full border-2 border-border shrink-0" />}
                  </button>
                ))}
              </div>
              <button onClick={() => selected.length > 0 && setStep(1)} disabled={selected.length === 0}
                className={`mt-6 w-full py-3 rounded-2xl text-sm font-semibold transition-colors flex items-center justify-center gap-2 ${
                  selected.length > 0 ? 'bg-foreground text-background hover:bg-foreground/90' : 'bg-muted text-muted-foreground cursor-not-allowed'}`}>
                Generate Documents <ChevronRight className="h-4 w-4" />
              </button>
            </div>
          </motion.div>
        )}

        {/* Step 2: Review Documents */}
        {step === 1 && (
          <motion.div key="step1" initial={{ opacity: 0, x: 20 }} animate={{ opacity: 1, x: 0 }} exit={{ opacity: 0, x: -20 }} className="space-y-6">
            {/* DMCA Notice */}
            <div className="rounded-3xl border border-border bg-card p-8 shadow-soft">
              <div className="flex items-center justify-between mb-4 flex-wrap gap-3">
                <div className="flex items-center gap-2">
                  <FileText className="h-5 w-5 text-brand-orange" />
                  <h3 className="font-display font-semibold">DMCA Takedown Notice</h3>
                </div>
                <button onClick={() => copyText(dmca, 'dmca')}
                  className="inline-flex items-center gap-1.5 px-4 py-2 rounded-full border border-border bg-muted/40 hover:bg-muted text-sm font-medium transition-colors">
                  {copied === 'dmca' ? <><CheckCircle2 className="h-4 w-4 text-emerald-500" /> Copied!</> : <><Copy className="h-4 w-4" /> Copy</>}
                </button>
              </div>
              <pre className="bg-muted/30 rounded-2xl p-5 text-xs font-mono leading-relaxed overflow-auto max-h-64 border border-border whitespace-pre-wrap">{dmca}</pre>
            </div>
            {/* Cease & Desist */}
            <div className="rounded-3xl border border-border bg-card p-8 shadow-soft">
              <div className="flex items-center justify-between mb-4 flex-wrap gap-3">
                <div className="flex items-center gap-2">
                  <Shield className="h-5 w-5 text-brand-purple" />
                  <h3 className="font-display font-semibold">Cease & Desist Letter</h3>
                </div>
                <button onClick={() => copyText(cd, 'cd')}
                  className="inline-flex items-center gap-1.5 px-4 py-2 rounded-full border border-border bg-muted/40 hover:bg-muted text-sm font-medium transition-colors">
                  {copied === 'cd' ? <><CheckCircle2 className="h-4 w-4 text-emerald-500" /> Copied!</> : <><Copy className="h-4 w-4" /> Copy</>}
                </button>
              </div>
              <pre className="bg-muted/30 rounded-2xl p-5 text-xs font-mono leading-relaxed overflow-auto max-h-64 border border-border whitespace-pre-wrap">{cd}</pre>
            </div>
            <div className="flex gap-3">
              <button onClick={() => setStep(0)} className="px-4 py-3 rounded-2xl border border-border text-sm font-medium hover:bg-muted/60 transition-colors flex items-center gap-2">
                <ArrowLeft className="h-4 w-4" /> Back
              </button>
              <button onClick={() => setStep(2)} className="flex-1 py-3 rounded-2xl bg-foreground text-background text-sm font-semibold hover:bg-foreground/90 transition-colors flex items-center justify-center gap-2">
                Proceed to Submit <ChevronRight className="h-4 w-4" />
              </button>
            </div>
          </motion.div>
        )}

        {/* Step 3: Submit Reports */}
        {step === 2 && (
          <motion.div key="step2" initial={{ opacity: 0, x: 20 }} animate={{ opacity: 1, x: 0 }} exit={{ opacity: 0, x: -20 }} className="space-y-6">
            <div className="rounded-3xl border border-border bg-card p-8 shadow-soft">
              <div className="flex items-center gap-2 mb-4">
                <AlertTriangle className="h-5 w-5 text-brand-orange" />
                <h3 className="font-display font-semibold">Submit Reports to Platforms</h3>
              </div>
              <p className="text-xs text-muted-foreground mb-6">Click each link below to open the platform&apos;s reporting page. Paste your DMCA notice when prompted.</p>
              <div className="space-y-3">
                {PLATFORMS.filter(p => selected.includes(p.id)).map(p => (
                  <div key={p.id} className="flex items-center justify-between rounded-2xl border border-border bg-muted/20 p-4">
                    <div className="flex items-center gap-3">
                      <div className={`h-8 w-8 rounded-lg ${p.color} flex items-center justify-center text-white text-sm font-bold`}>{p.icon}</div>
                      <span className="text-sm font-medium">{p.name}</span>
                    </div>
                    <div className="flex items-center gap-2">
                      <button onClick={() => copyText(dmca, `report-${p.id}`)}
                        className="inline-flex items-center gap-1 px-3 py-1.5 rounded-xl border border-border text-xs font-medium hover:bg-muted transition-colors">
                        {copied === `report-${p.id}` ? <><CheckCircle2 className="h-3 w-3 text-emerald-500" /> Copied</> : <><Copy className="h-3 w-3" /> Copy Notice</>}
                      </button>
                      <a href={p.reportUrl} target="_blank" rel="noopener noreferrer"
                        className="inline-flex items-center gap-1 px-3 py-1.5 rounded-xl bg-brand-orange text-white text-xs font-medium hover:bg-brand-orange/90 transition-colors">
                        Report <ExternalLink className="h-3 w-3" />
                      </a>
                    </div>
                  </div>
                ))}
              </div>
            </div>
            <div className="rounded-3xl border border-emerald-500/30 bg-emerald-500/5 p-6">
              <div className="flex items-start gap-3">
                <CheckCircle2 className="h-5 w-5 text-emerald-500 shrink-0 mt-0.5" />
                <div>
                  <h4 className="font-display font-semibold text-sm">What happens next?</h4>
                  <p className="text-xs text-muted-foreground mt-1 leading-relaxed">
                    Most platforms respond to DMCA requests within 24-48 hours. Keep your Trinetra analysis report as evidence.
                    If the content isn&apos;t removed, consider consulting a digital rights attorney — see the Crisis Support tab for pro-bono legal resources.
                  </p>
                </div>
              </div>
            </div>
            <button onClick={() => setStep(0)} className="px-4 py-3 rounded-2xl border border-border text-sm font-medium hover:bg-muted/60 transition-colors flex items-center gap-2">
              <ArrowLeft className="h-4 w-4" /> Start Over
            </button>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
};
